name = "Placeholder"
author = "Maddie, Linyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12bd8ba1e3218672c4120378e930cc9b51f765a2ffd81ec95df546faf0b1fd40"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
