name = "Placeholder"
author = "Maddie, Linyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4349492d0fce4e39bfe891e21f97bf47f128a9fcee78115e0bf14b008cb75cd5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
